### PR TITLE
fix example URL

### PR DESCRIPTION
**Pull request by tomByrer**
didn't work; color was too short

I assume this will also fix the landing page?

### CODE REVIEW

**Comment by Cherry** [comment]
Thanks for the PR! The landing page is just a static `index.html` in the `public` folder if you wouldn't mind updating that too? (There's no fancy build-chain here yet).

**Comment by Cherry** [comment]
Also, the example URL seems to work just fine for me? It's probably missing a `textColor` such as `https://images.placeholders.dev/?width=350&height=100&text=Hello%20World&bgColor=%23000&textColor=rgba(255,255,255,0.5)`, but the short `bgColor` seems to work fine here? Perhaps it's a browser-specific thing?

**Comment by tomByrer** [comment]
> Perhaps it's a browser-specific thing?

Maybe, Firefox Dev on Win10.  Dark mode but perhaps shouldn't matter?

placeholder-dev-demo-firefox

**Comment by tomByrer** [comment]
Hold on, I have a better idea  🌱

**Comment by tomByrer** [comment]
A little more advertising never hurts ;)

**Review by Cherry — APPROVED** [review]

**Comment by Cherry** [comment]
Thanks, merged!

**Pull request merged**
